services:
  ctrl:
    build: .
    ports:
      - "1337:1337"
    environment:
      - TARGET_URL=https://github.com/leraptor65
      - SCALE_FACTOR=1.0
      - AUTO_SCROLL=false
      - SCROLL_SPEED=10
      - SCRIPT_DIR=/host
    volumes:
      - ./data:/app/data
      - ./:/host
    security_opt:
      - seccomp:unconfined
