services:
  ctrl:
    build: .
    ports:
      - "${CTRL_PORT}:1337"
    env_file:
      - .env
    environment:
      - SCRIPT_DIR=/host
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
      - ./:/host
    security_opt:
      - seccomp:unconfined
